adminpanel/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'adminpanel'



urlpatterns = [
    path('dashbord/',views.dashbord, name='dashbord'),
    path('users/',views.userslist, name='userslist'),
    path('users/toggle_status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('users/adduser/',views.adduser,name='adduser'),
    path('category/',views.categorylist, name='categorylist'),
    path('category/delete_category/<int:category_id>/',views.delete_category, name='delete_category'),
    path('category/update_category/<int:category_id>/',views.update_category,name='update_category'),
    path('category/addcategory/',views.addcategory,name='addcategory'),
    path('subcategory/',views.subcategorylist,name='subcategorylist'),
    path('subcategory/delete_subcategory/<int:subcategory_id>/',views.delete_subcategory, name='delete_subcategory'),
    path('subcategory/update_subcategory/<int:subcategory_id>/',views.update_subcategory, name='update_subcategory'),
    path('subcategory/addsubcategory/',views.addsubcategory,name='add_subcategory'),
    path('product/',views.productlist,name='productlist'),
    path('product/addproduct/',views.addproduct,name='add_product'),
    path('product/delete_product/<int:product_id>/',views.delete_product,name='delete_product'),
    path('product/update_product/<int:product_id>/',views.update_product,name='update_product'),
    path('orders/',views.orderslist,name='orderslist'),
    path('update_order/<int:id>',views.update_order,name="update_order"), 
    path('admin_search/', views.adminsearch,name='adminsearch'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('cart/',views.cartpage,name='cartpage'),
  path('add_cart/<int:product_id>/', views.add_cart,name='add_cart'),
  path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart,name='remove_cart'),
  path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item,name='remove_cart_item'),
  path('checkout/',views.checkout,name='checkout'),
  path('deleteCheckoutAddress/<int:id>/', views.deleteCheckoutAddress, name='deleteCheckoutAddress'),
  path('AddCheckoutAddress/', views.AddCheckoutAddress, name='AddCheckoutAddress'),
]

home/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('',views.home, name='home'),
    path('category/',views.categoryy, name='category'),
    path('sub_category/<slug:sub_category_slug>/', views.categoryy,name='product_by_sub_category'),
    path('product/<int:product_id>/',views.productdetails,name='product'),
    path('dashbord/search/', views.search,name='search'),
    
   
]

project2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('adminpanel/', include('adminpanel.urls',  namespace='adminpanel')),
    path('account/', include('account.urls')),
    path('category/',include('category.urls')),
    path('orders/',include('orders.urls')),
    path('userprofile/',include('userprofile.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from account.models import CustomUser
from category.models import product

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    order_id = models.CharField(max_length=100,blank=True,default='empty')
    payment_method = models.CharField(max_length=100)
    amount_paid = models.FloatField(default=0)
    status = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.payment_id
    


class Order(models.Model):
    STATUS = (
        ('Order Confirmed', 'Order Confirmed'),
        ('Shipped',"Shipped"),
        ('Out for delivery',"Out for delivery"),
        ('Delivered', 'Delivered'),
        ('Cancelled','Cancelled'),
        ('Returned','Returned'),
    )
    user = models.ForeignKey(CustomUser,on_delete=models.SET_NULL,null=True)
    payment = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50,blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100,blank=True)
    order_total = models.FloatField()
    order_discount = models.FloatField(default=0)
    tax = models.FloatField()
    status = models.CharField(max_length=50,choices=STATUS,default='Order Confirmed')
    ip = models.CharField(blank=True,max_length=20)
    is_ordered = models.BooleanField(default=False)
    is_returned = models.BooleanField(default=False)
    return_reason = models.CharField(max_length=50, blank=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
   
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name 
    

class OrderProduct(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='user_order_page')
    payment = models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    product = models.ForeignKey(product,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.product.product_name
    def sub_total(self):
        return self.product.price * self.quantity

category/views.py
from django.shortcuts import render,redirect
from category.models import category,subcategory,product,cart,cartitem
from django.http import HttpResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
import uuid
from userprofile.models import Address
from userprofile.forms import AddressForm
from django.contrib import messages
# Create your views here.

def _cart_id(request, user=None):
    if user and user.is_authenticated:
        # Use the user's ID as part of the cart identifier for authenticated users
        return f"user_{user.id}"
    else:
        cart = request.session.get('cart_id')
        if not cart:
            # If no cart_id exists in the session, create a new one
            cart = f"guest_{uuid.uuid4().hex[:5]}"
            request.session['cart_id'] = cart

        return cart

def add_cart(request, product_id):
    current_user = request.user

    try:
        productt = product.objects.get(id=product_id)
    except product.DoesNotExist:
        # Handle the case where the product does not exist
        return redirect('cartpage')

    if current_user.is_authenticated:
        cart_id = _cart_id(request, user=current_user)
    else:
        cart_id = _cart_id(request)

    try:
        cart_instance = cart.objects.get(cart_id=cart_id)
    except cart.DoesNotExist:
        cart_instance = cart.objects.create(cart_id=cart_id, user=current_user if current_user.is_authenticated else None)
        cart_instance.save()

    is_cart_item_exists = cartitem.objects.filter(product=productt, cart=cart_instance, user=current_user if current_user.is_authenticated else None).exists()
    if is_cart_item_exists:
        cart_item = cartitem.objects.get(product=productt, cart=cart_instance, user=current_user if current_user.is_authenticated else None)
        cart_item.quantity += 1
        cart_item.save()
    else:
        cart_item = cartitem.objects.create(product=productt, quantity=1, cart=cart_instance, user=current_user if current_user.is_authenticated else None)

    return redirect('cartpage')

def remove_cart(request,product_id,cart_item_id):
    
    productt = get_object_or_404(product,id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item =cartitem.objects.get(product=productt,user=request.user,id=cart_item_id)
        else:
            cartt = cart.objects.get(cart_id = _cart_id(request))    
            cart_item =cartitem.objects.get(product=productt,cart=cartt,id=cart_item_id)
        if cart_item.quantity > 1:
          cart_item.quantity -= 1
          cart_item.save()
    
        else:
          cart_item.delete()
    except:
        pass
    return redirect('cartpage')  

def remove_cart_item(request,product_id,cart_item_id):
    productt = get_object_or_404(product,id=product_id)
    if request.user.is_authenticated:
        cart_item = cartitem.objects.get(product=productt,user=request.user,id=cart_item_id)
    else:
        cartt = cart.objects.get(cart_id= _cart_id(request))
        cart_item = cartitem.objects.get(product=productt,cart=cartt,id=cart_item_id)
    cart_item.delete()
    return redirect('cartpage')  


 

def cartpage(request,total=0, quantity=0, cart_items=None):


 try:
    tax=0
    grand_total=0
    if request.user.is_authenticated:
           cart_items = cartitem.objects.filter(user=request.user,is_active=True)
    else:
        cartt= cart.objects.get(cart_id= _cart_id(request))
        cart_items= cartitem.objects.filter(cart=cartt,is_active=True)
    for cart_item in cart_items:
        total +=(cart_item.product.price* cart_item.quantity)
        quantity+= cart_item.quantity
        tax =(2 * total)/100
        grand_total = total + tax 

 except :
        pass #just ignoe
 context = {
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax' : tax,
        'grand_total': grand_total
        
    }
      
    
 return render(request,'cart.html',context)

@login_required(login_url='loginn')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = None
    grand_total = None
    address = Address.objects.filter(user = request.user)
    form = AddressForm()
    

    try:
        if request.user.is_authenticated:
            cart_items = cartitem.objects.filter(user=request.user, is_active=True)
        else:
            cartt = cart.objects.get(cart_id=_cart_id(request))
            cart_items = cartitem.objects.filter(cart=cartt, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax    
    except ObjectDoesNotExist:
        pass  # just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
        'address':address,
        'form':form,
       
    }

    return render(request, 'checkout.html', context)


def deleteCheckoutAddress(request,id):
    address=Address.objects.get(id = id)
    messages.success(request,"Address Deleted")
    address.delete()
    return redirect('checkout')


def AddCheckoutAddress(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            print('form is valid')
            detail = Address()
            detail.user = request.user
            detail.first_name =form.cleaned_data['first_name']
            detail.last_name = form.cleaned_data['last_name']
            detail.phone =  form.cleaned_data['phone']
            detail.email =  form.cleaned_data['email']
            detail.address_line1 =  form.cleaned_data['address_line1']
            detail.address_line2  = form.cleaned_data['address_line2']
            detail.state =  form.cleaned_data['state']
            detail.city =  form.cleaned_data['city']
            detail.save()
            messages.success(request,'Address added Successfully')
            return redirect('checkout')
        else:
            messages.error(request,'Form is Not valid')
            return redirect('checkout')
  

home/views.py
from django.shortcuts import render,redirect
from category.models import category,subcategory,product,cartitem
from django.shortcuts import render, get_object_or_404
from category.views import _cart_id
from django.db.models import Q
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator

# Create your views here.

def home(request):
     products= product.objects.all().filter(is_available=True)[:4]
     context= {
          'products': products,
     }
     return render(request,'home.html',context)

def categoryy(request,sub_category_slug=None):
    sub_category = None
    products = None
    categories = None
    
    
    if sub_category_slug !=None:
        print("hoooy")
        sub_category = get_object_or_404(subcategory,slug=sub_category_slug)
        products = product.objects.filter(sub_category=sub_category,is_available=True)
        categories = category.objects.all()
        sub = subcategory.objects.all()
        Paginattor= Paginator(products,3)
        page= request.GET.get('page')
        paged_products= Paginattor.get_page(page)
        
        
    else:
        
        categories = category.objects.all()
        sub = subcategory.objects.all()
        products = product.objects.all()
        Paginattor= Paginator(products,6)
        page= request.GET.get('page')
        paged_products= Paginattor.get_page(page)

        
    context = {
        'categories' : categories,
        'sub':sub,
        'products':paged_products,
        
    }
    return render(request,'fcategory.html',context)

def productdetails(request,product_id):
    singleproduct= product.objects.get(id=product_id)
    in_cart= cartitem.objects.filter(cart__cart_id=_cart_id(request), product=singleproduct).exists()
    context6={
        'singleproduct':singleproduct,
        'in_cart' : in_cart
    }
    return render(request,'fproduct.html',context6)

def search(request):
   categories = category.objects.all()
   sub = subcategory.objects.all()
   products = None
   if 'keyword' in request.GET:
       keyword = request.GET['keyword']
       if keyword:
           products = product.objects.order_by('-created_at').filter(Q(description__icontains=keyword)|Q(product_name__icontains=keyword))
           
           print('kooooi')
       else:
           return redirect('home')
   context = {
          'products':products,
          'categories':categories,
          'sub':sub

        }       
   return render(request,'fcategory.html',context)

templates/adminbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DOBLE Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
          <a class="sidebar-brand brand-logo" href="{% static 'dashbord.html' %}"><img src="{% static 'assets/images/logo.svg' %}" alt="logo" /></a>
          <a class="sidebar-brand brand-logo-mini" href="{% static 'index.html' %}"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
        </div>
        <ul class="nav">
          <li class="nav-item profile">
            <div class="profile-desc">
              <div class="profile-pic">
                <div class="count-indicator">
                  <img class="img-xs rounded-circle " src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                  <span class="count bg-success"></span>
                </div>
                <div class="profile-name">
                  <h5 class="mb-0 font-weight-normal">Anshida</h5>
                  <span>Admin</span>
                </div>
              </div>
              <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
              <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-settings text-primary"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-onepassword  text-info"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-calendar-today text-success"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
                  </div>
                </a>
              </div>
            </div>
          </li>
          <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminpanel:dashbord' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
        </li>
        <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'adminpanel:dashbord' %}">
            <span class="menu-icon">
              <i class="mdi mdi-speedometer"></i>
            </span>
            <span class="menu-title">salesreport</span>
          </a>
        </li>
          <li class="nav-item menu-items {% if '/userslist/' in request.path %}active{% endif %}">
          
            <a class="nav-link" href="{% url 'adminpanel:userslist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Users</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminpanel:categorylist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Catogory</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminpanel:subcategorylist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Sub catogory</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminpanel:productlist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Products</span>
            </a>
          </li>
         
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminpanel:orderslist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Orders</span>
            </a>
          </li>
        </ul>
      </nav>

       <!-- partial -->
      
       <div class="container-fluid page-body-wrapper bg-dark">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar p-0 fixed-top d-flex flex-row">
          
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button
              class="navbar-toggler navbar-toggler align-self-center"
              type="button"
              data-toggle="minimize"
            >
              <span class="mdi mdi-menu"></span>
            </button>
            <ul class="navbar-nav w-100">
              <li class="nav-item w-100">
                <form  id="form" class="nav-link mt-2 mt-md-0 d-none d-lg-flex search" action="{% url 'adminpanel:adminsearch' %}" method="GET">
                  <input
                    type="text"
                    class="form-control"
                    id="search_input"
                    placeholder="Search products"
                    name="keyword"
                  />
                   <button type="submit" class="btn btn-primary m-1" style="height:33px;width:74px;">search</button>
                   
                </form>
              </li>
              <li class="nav-item menu-items">
                <a class="nav-link" href="{% url 'logout' %}">
                 
                  <span class="menu-title">Logout</span>
                </a>
              </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right">
              
              <li class="nav-item dropdown">
                <a
                  class="nav-link"
                  id="profileDropdown"
                  href="#"
                  data-toggle="dropdown"
                >
                  <div class="navbar-profile">
                    <img
                      class="img-xs rounded-circle"
                      src="{% static 'assets/images/faces/face15.jpg'%}"alt=""/>
                    <p class="mb-0 d-none d-sm-block navbar-profile-name">Anshida</p>
                   </div>
                </a>
             
              </li>
            </ul>
            <button
              class="navbar-toggler navbar-toggler-right d-lg-none align-self-center"
              type="button"
              data-toggle="offcanvas"
            >
              <span class="mdi mdi-format-line-spacing"></span>
            </button>
          </div>
        </nav>
        <!-- partial -->
        <div class="bg-dark pt-5 mt-5" style='width:100%;height:100%'>
        {%block content%}
        {%endblock%}
        </div>
      </div>
    </div>
    

    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'assets/vendors/chart.js/Chart.min.js'%}"></script>
    <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js'%}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js'%}"></script>
    <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js'%}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js'%}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
    <script src="{% static 'assets/js/misc.js'%}"></script>
    <script src="{% static 'assets/js/settings.js'%}"></script>
    <script src="{% static 'assets/js/todolist.js'%}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'assets/js/dashboard.js'%}"></script>
    <!-- End custom js for this page -->
    <!-- search -->
    <script src="{% static 'js/search.js'%}"></script>
  </body>
</html>

templates/category.html
{% extends 'adminbase.html' %}
{% load static %}

{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Doble Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

</head>

<body>

  <div class="row ">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body bg-dark">
          <div class="text-center  pb-2"><a href="{% url 'adminpanel:addcategory' %}" class="btn btn-primary btn-md">+</a>
          </div>
        </div>

        <div class="table-responsive bg-dark">
          <table class="table">
            <thead>
              <tr>

                <th> id </th>
                <th> categoryname </th>
                <th> createdat </th>
                <th> updatedat </th>
                <th> Action</th>
               
              </tr>
            </thead>
            <tbody>
              {% for i in categories %}
              <tr>
                <td>{{i.id}}</td>
                <td>{{i.category_name}}</td>
                <td>{{i.created_at}}</td>
                <td>{{i.updated_at}}</td>
                <td><a href="{% url 'adminpanel:delete_category' category_id=i.id %}" class="btn btn-danger btn-sm">Delete</a>
                <a href="{% url 'adminpanel:update_category'  category_id=i.id %}" class="btn btn-warning btn-sm">update</a></td>
              </tr>
             {% endfor %}      
        </tbody>
        </table>

             <!-- Start pagination -->
             <nav class="mb-3 mt-3" aria-label="page navigation sample">
              {% if categories.has_other_pages %}
                <ul class="pagination">
                {% if categories.has_previous %}
                  <li class="page-item"><a class="page-link "href="?page={{categories.previous_page_number}}">Previous</a></li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link "href="#">Previous</a></li>
                  {% endif %}
                  {% for i in categories.paginator.page_range %}
                  {% if categories.number == i %}
                   <li class="page-item active"><a class="page-link "href="#">{{i}}</a></li>
                   {% else %}
                   <li class="page-item"><a class="page-link "href="?page={{i}}">{{i}}</a></li>
                   {% endif %}
                   {% endfor %}
                   {% if categories.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{categories.next_page_number}}">Next</a></li>
                  {% else %}
                   <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                  {% endif %}
                </ul>
                {% endif %}
              </nav>
              <!-- End pagination -->
      </div>
























      <!-- partial -->
    </div>
    <!-- main-panel ends -->
  </div>
  <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
  <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
  <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
  <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js' %}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'assets/js/misc.js' %}"></script>
  <script src="{% static 'assets/js/settings.js' %}"></script>
  <script src="{% static 'assets/js/todolist.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/dashboard.js' %}"></script>
  <!-- End custom js for this page -->
</body>

</html>




{% endblock content %}